Dagger
worldsnas/StarPlayer pull request #12
Opened 2020-03-05 08:36 UTC by neptu39701

2020-03-05 10:52 UTC, helloseyedjafari requested changes
Good start
now let's refactor!!

2020-03-05 10:52 UTC, worldsnas commented on app/build.gradle
> +    implementation 'com.google.dagger:dagger:2.11'
lotfan az file `dependencies.gradle` estefade konid

2020-03-05 10:52 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/MainApplication.kt
> +        lateinit var mainApplicationComponent: MainApplicationComponent
khaheshan ta jayi ke mishe az `static` dori konid
toye `application` niazi nist static 
harja niaz bashe ba `context.aplicationContext` mishe gereftesh va rosh function call kard

2020-03-05 10:52 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/MainApplication.kt
> +            DaggerPlayerFragmentComponent.builder().androidmodule(Androidmodule(this)).build()
in mage baraye fragment nist?
chera inja dare sakhte mishe?

2020-03-05 10:52 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/Androidmodule.kt
> +class Androidmodule (private val application: Application){
lotfan az pass dadane maghadir be module ha dori konid
mitonid bejash az `@BindsInstance` estefade konid

2020-03-05 10:52 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/Androidmodule.kt
> +    fun provideApplicationContext():Context = application
bejaye function hayi ke faghat cast mikonan mitonin az `@Binds` estefade konin va `abstract module class`

2020-03-05 10:52 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/MainApplicationComponent.kt
> +    fun inject (context: MainActivity)
in component baraye kole application e
chera bayad `MainActivity` ro to in scope inject konim?
`MainActivity` age niaz dare mitone inject e khodesho dashte bashe

2020-03-05 10:52 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentComponent.kt
> +@Component (modules = [Androidmodule::class])
benazaram bad nist ye dependency be `ApplicationComponent` bedim
key dependency hayi ke to scope e application niaz hastan va provide mishan ro azash begirim

2020-03-05 10:52 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +        MainApplication.playerFragmentComponent.inject(this)
behtare haminja sakhte beshe component

2020-03-05 12:11 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/di/MainApplicationComponent.kt
> +    fun inject (context: MainActivity)
یعنی یه کامپوننت برای اکتیویتی درست کنم؟

2020-03-05 12:56 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/MainApplicationComponent.kt
> +    fun inject (context: MainActivity)
age niaze bale

2020-03-10 15:44 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentComponent.kt
> +@Component (modules = [Androidmodule::class])
اینو متوجه نشدم، میشه بیشتر توضیح بدید؟

2020-03-10 20:54 UTC, helloseyedjafari requested changes
much better 
good job

2020-03-10 20:54 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentComponent.kt
> +        fun playerFragment(playerFragment: PlayerFragment): Builder
niaz darim vaghean be fragment dakhele graph?

2020-03-10 20:54 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +        playerFragmentComponent = DaggerPlayerFragmentComponent.builder().build()
parameter haro pass nadadin
crash mikone

2020-03-10 20:59 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentComponent.kt
> +        fun playerFragment(playerFragment: PlayerFragment): Builder
اصولا مگه نباید به appComponent 
وصل باشه؟

2020-03-11 07:19 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentComponent.kt
> +@Component (modules = [Androidmodule::class])
component ha mitonan be ham dependency dashte bashan

mamolan to android hame ye feature component ha be `AppComponent` niaz daran
manam goftam bad nist ma ham az hamin aval in dependency ro dashte bashim

2020-03-11 07:19 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentComponent.kt
> +        fun playerFragment(playerFragment: PlayerFragment): Builder
soaletono nafahmidam
man roye `PlayerFragment` comment gozashtam

2020-03-11 09:53 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentComponent.kt
> +        fun playerFragment(playerFragment: PlayerFragment): Builder
منظور شما اینه که فرگمنت رو نیارم توی گراف appComponent 
درسته؟

2020-03-11 12:05 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +        playerFragmentComponent = DaggerPlayerFragmentComponent.builder().build()
یعنی appComponent?
رو اینطوری بهش بدم ؟
https://github.com/Shayan-Sakhaei/TasteV2/blob/70c48e3115aedd4cb7e5232a0b63693cca19d69b/app/src/main/java/ir/apptaste/android/view/fragment/DetailFragment.kt#L37

2020-03-11 12:10 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/AppComponent.kt
> +interface AppComponent {
behtare scope e `Singleton` ro be appComponent bedim

2020-03-11 12:10 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +        playerFragmentComponent = DaggerPlayerFragmentComponent.builder().build()
injori ham mitonid

2020-03-11 21:12 UTC, helloseyedjafari requested changes
good job

2020-03-11 21:12 UTC, helloseyedjafari commented on app/src/main/java/com/worldsnas/starplayer/MainActivity.kt
> +        val view = binding.root
fek nemikonam be in `view` niazi bashe

2020-03-11 21:12 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
nemishe `val` tarif kard?
fek konam to activity beshe

2020-03-11 21:12 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/Androidmodule.kt
> +class Androidmodule (private val application: Application){
in file hamchenan niaze?

2020-03-11 21:12 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/Androidmodule.kt
> +    fun provideApplicationContext():Context = application
inam niaze hanoz?

2020-03-11 21:12 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/MainApplicationComponent.kt
> +    fun inject (context: MainActivity)
in hanoz niaze?

2020-03-11 21:12 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentComponent.kt
> +interface PlayerFragmentComponent {
ahsant

2020-03-11 21:12 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentScope.kt
> +annotation class PlayerFragmentScopegit
esme behtar nemishe?!!!

2020-03-11 22:20 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentScope.kt
> +annotation class PlayerFragmentScopegit
on git ro havasam naboode bbakhshid, PFScope khobe?

2020-03-11 22:43 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
توی raywenderlich همینو زده 
اگه بخوام جایگزین کنم، باید با nullable 
ها بنویسم یا 
با lazy

2020-03-12 06:21 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/MainActivity.kt
> +        val view = binding.root
اینا رو من ننوشتم از dev گرفتم
ویرایش کنم؟

2020-03-12 07:08 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/MainActivity.kt
> +        val view = binding.root
bi zahmat!!

2020-03-12 07:09 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentScope.kt
> +annotation class PlayerFragmentScopegit
ScreenScope
ya 
FragmentScope
ya 
FeatureScope

ina chetoran?

2020-03-12 07:18 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/di/PlayerFragmentScope.kt
> +annotation class PlayerFragmentScopegit
FragmentScope khobe

2020-03-13 15:16 UTC, helloseyedjafari approved these changes
awesome

2020-03-13 15:19 UTC, merged