Add MusicExplorer
worldsnas/StarPlayer pull request #24
Opened 2020-04-01 16:37 UTC by neptu39701

2020-04-01 16:59 UTC, helloseyedjafari requested changes
nice start
now let's finish it

2020-04-01 16:59 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +class MusicExplorer {
1. fek mikonam esme monasebi nabase
2. behtare yek interface besazid va azash extend konid
3. `ContentResolver` behtare toye constructor daryaft beshe na parameter bashe

2020-04-01 16:59 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +        MediaStore.Audio.Media._ID,
pas address e file chi?
yani chetori ma in file ro lay konim vaghti nemidonim kojast?

2020-04-01 16:59 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +        return GlobalScope.async(IO) {
lotfan behich vajh az `GlobalScope` estefade nakonin
inja behtare function ro `suspend` konin va baraye taghyir coroutine az `withContext` estefade konin

2020-04-01 17:03 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +class MusicExplorer {
من واقعا سلیقه خوبی برای انتخاب اسم ندارم :) ، لطفا پیشنهاد بدید

2020-04-01 18:39 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +        MediaStore.Audio.Media._ID,
deprecate شده بود :)
دنبال جایگزینم

2020-04-01 21:15 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +class MusicExplorer {
البته که سلیقه ای نیست و یکی از هنر های دولوپر بنظرم انتخاب اسم مناسبه
من 
LocalMusicProvider 
می تونم پیشنهاد بدم. ولی می تونین از دیگران نظر بپرسین

2020-04-01 21:21 UTC, helloseyedjafari requested changes
way to go
keep it up

2020-04-01 21:21 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/GetAllMusic.kt
> +    suspend fun getAllMusic() : ArrayList<Music>
lotfan ta jaye momken az `abstraction` estefade konin
inja mitonin `List<Music>` bar gardonin

2020-04-01 21:21 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/GetAllMusic.kt
> +interface GetAllMusic {
esme ino ham tebghe onyeki bezarin (be comment haye ghabli tavajoh konin)
va baraye piade sazish mitnonin az `impl+(interfaceName)` estefade konin

2020-04-01 21:21 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +constructor(val contentResolver: ContentResolver) : GetAllMusic {
`private val` bashe benazaram behtare

2020-04-01 21:21 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +            return@withContext musics
to `lambda` niazi nist be `return`

2020-04-01 21:21 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +                cursor.close()
benazaram baraye in az `try-with-resources` estefade konin kheili behtare

2020-04-01 21:23 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +        MediaStore.Audio.Media._ID,
shayad in komak kone:

https://github.com/Farajialireza82/Star-Player/blob/fcd558b47643bfe4bcae6470147bc5d6d5666647/app/src/main/java/com/example/galaxyplayerkotlin/repositories/SongListRepo.java#L43

2020-04-02 13:01 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +        MediaStore.Audio.Media._ID,
MediaStore.Audio.Media.DATA
 دقیقا همین منسوخ شده

2020-04-02 15:01 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +class MusicExplorer {
همین خوبه به نظرم

2020-04-02 15:03 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +            return@withContext musics
چطور؟
آخه تابع برگشت داره، نمیشه برداشت که

2020-04-02 17:25 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +            return@withContext musics
niazi be neveshtan nis
syntax e kotlin e

2020-04-02 17:25 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +        MediaStore.Audio.Media._ID,
خب معمولا توی توضیاحتش می نویسن چی جایگزین کنین

2020-04-02 17:27 UTC, helloseyedjafari requested changes
Well done

2020-04-02 17:27 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/LocalMusicProviderImpl.kt
> +interface LocalMusicProviderImpl {
`impl` yani piade sazi
in interface e behtare esm o tanha bezarid

2020-04-02 17:27 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/LocalMusicProvider.kt
> +class LocalMusicProvider @Inject
`impl` ro inja ezafe konid

2020-04-02 17:31 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/LocalMusicProviderImpl.kt
> +interface LocalMusicProviderImpl {
درسته من اشتباه کردم

2020-04-02 19:04 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +            return@withContext musics
برداشتم قرمز شد، فکر کنم خوب منظورتون رو متوجه نشدم

2020-04-03 09:38 UTC, hosseiniSeyRo commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +        return GlobalScope.async(IO) {
اگه بجای GlobalScop از اسکوپ ویومدل استفاده کنیم بهتر نیست؟

2020-04-03 17:06 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +        return GlobalScope.async(IO) {
الان داره از 
withContext 
استفاده می کنه، خوب نیست؟

2020-04-03 17:44 UTC, helloseyedjafari requested changes
almost there
well done

2020-04-03 17:44 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/LocalMusicProviderImpl.kt
> +                        contentUri.toString()
`contentUri.path` ya shabihesh bezanid fek konam behtare

2020-04-03 17:44 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/Music.kt
> -    val genre: String
genre niaz nis hazf beshe ha

2020-04-03 17:44 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/Music.kt
> +    val uri: String
uri kheili esme bi mani ye
lotfan behtar entekhab konid

2020-04-03 17:44 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +        return GlobalScope.async(IO) {
chera intori kheili behtare
scope ro laye haye balatar (viewModel) mitonan handle konan

2020-04-03 19:52 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +        return GlobalScope.async(IO) {
یعنی ویومدل launch میکنه؟

2020-04-03 22:16 UTC, helloseyedjafari requested changes
hopefully last one

2020-04-03 22:16 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/LocalMusicProviderImpl.kt
> +    override suspend fun getAllMusic(): List<Music> {
chera `withContext` ro hazf kardi?
on mohem bod

2020-04-03 22:16 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/LocalMusicProviderImpl.kt
> +                    contentUri.path.toString()
`path` mage khodesh string nist? niaze dobare `toString()` bezanim?

2020-04-04 03:31 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/LocalMusicProviderImpl.kt
> +                    contentUri.path.toString()
چون nullable بود خودش، باید مدل رو 
باید مدل رو nullable می‌کردم تا بتونم استفاده کنم
یا این toString رو اضافه کنم

2020-04-04 03:47 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/LocalMusicProviderImpl.kt
> +    override suspend fun getAllMusic(): List<Music> {
قرار نشد launch توی ویو مدل باشه؟🤔
(از ویومدل اسکوپ استفاده کنیم؟)
https://github.com/RadheshyamSingh/Coroutine-With-Lifecycle-Architectural-Components/blob/master/coroutine-lifecycle/app/src/main/java/com/radheshyam/coroutinelifecycledemo/repository/EmployeeRepository.kt


https://github.com/RadheshyamSingh/Coroutine-With-Lifecycle-Architectural-Components/blob/master/coroutine-lifecycle/app/src/main/java/com/radheshyam/coroutinelifecycledemo/viewmodel/MainActivityViewModel.kt

https://proandroiddev.com/coroutines-with-architecture-components-4c223a51b112

2020-04-04 10:55 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +            return@withContext musics
eybi nadare bashe baadan

2020-04-04 10:55 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/model/MusicExplorer.kt
> +        return GlobalScope.async(IO) {
می تونه بله
شایدم طوری دیگه استفاده کنه
که الان ما نمی دونیم.

2020-04-04 11:00 UTC, helloseyedjafari requested changes
please finish it!

2020-04-04 11:00 UTC, helloseyedjafari commented on app/src/main/java/com/worldsnas/starplayer/model/LocalMusicProviderImpl.kt
> +    override suspend fun getAllMusic(): List<Music> {
khob che rabti be `withContext` dare
ma ba in function migim dispatcher in tike code chi bashe
hala harki va harjori ejra karde bashe

2020-04-04 11:00 UTC, helloseyedjafari commented on app/src/main/java/com/worldsnas/starplayer/model/LocalMusicProviderImpl.kt
> +                    contentUri.path.toString()
na dige nashod!
alan age null bashe khorojish mishe `"null"`
age null e benazaram aslan ezafe nakonim in item ro be list cho manteghan bedard nemikhore!!!

2020-04-04 12:25 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/model/LocalMusicProviderImpl.kt
> +                    contentUri.path.toString()
https://gist.github.com/neptu39701/3f9f9aa71d51b8bfe16223698994a8bd
intori khobe handle bshe?

2020-04-05 08:34 UTC, helloseyedjafari approved these changes
Well done,
you did it

2020-04-05 08:55 UTC, merged