Play single music
worldsnas/StarPlayer pull request #25
Opened 2020-04-02 21:24 UTC by MohammadFakhraee

Setup ExoPlayer & bind to view controller & play a music

2020-04-03 06:47 UTC, helloseyedjafari requested changes
afarin khobe
yeseri taghirate kochik

2020-04-03 06:47 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +    lateinit var viewBinding: FragmentPlayerBinding
in bayad null beshe vagarna leak mikone

2020-04-03 06:47 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +        val mediaSource = buildMediaSource(Uri.parse("asset:///take_your_time.mp3"))
gharar bod az roye file bekhone
in az asset mikhone

2020-04-03 06:47 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +        val dataSourceFactory = DefaultDataSourceFactory(context, "Star-player")
context inja `nullable` e 
behtare `!!` bezanid

2020-04-03 06:47 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +        initializeExoplayer()
behtare to `onCreate` seda zade beshe

2020-04-03 06:47 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +        playWhenReady = exoPlayer.playWhenReady
intori negah dashtan maghadir fayde i nadare
be nazaram felan p
akesh konin behtar bashe

2020-04-03 06:47 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +        viewBinding.exoControlView.player = exoPlayer
toye `onDestroyView` bayad null she fek konam

2020-04-03 10:36 UTC, hosseiniSeyRo commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +    lateinit var viewBinding: FragmentPlayerBinding
اینو به فرگمنت اضافه کنین
 override fun onDestroyView() {
        super.onDestroyView()
        viewBinding = null
    }

2020-04-03 10:38 UTC, hosseiniSeyRo commented on app/src/main/java/com/worldsnas/starplayer/view/PlayerFragment.kt
> +        val mediaSource = buildMediaSource(Uri.parse("asset:///take_your_time.mp3"))
من قبلا اینو برای خوندن از فایل تو جاوا استفاده کرده بودم. حالا قطعا کاتلینشم مشابه همین میشه. امتحانش کنید لطفا
    private String filePath = Environment.getExternalStorageDirectory().getPath() + "/" + "Download" + "/Temp/" + "kaj.mp4";

2020-04-11 18:30 UTC, helloseyedjafari approved these changes
That's my boy!

2020-04-11 18:31 UTC, merged