Mrh OnlineMusicList Page
worldsnas/StarPlayer pull request #32
Opened 2020-04-30 11:56 UTC by mahdi302

This page is as same as music List page but its uses for shows Online kinds of music

2020-04-30 12:52 UTC, helloseyedjafari requested changes
you could choose a better branch name
good job small changes and integerate with repo and we are done here

2020-04-30 12:52 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/view/online_music_list/OnlineMusicListFragment.kt
> + * created by Roohandeh  4/29/2020
pak kon lotfan

2020-04-30 12:52 UTC, worldsnas commented on app/src/main/java/com/worldsnas/starplayer/view/online_music_list/OnlineMusicListFragment.kt
> +    lateinit var onlineMusicListViewModel: OnlineMusicListViewModel
`ViewModel` injori nabayad sakhte beshe

2020-04-30 12:52 UTC, worldsnas commented on app/src/main/res/values/dimens.xml
> +    <dimen name="eight_dp">8dp</dimen>
esm haye behtar bezar lotfan

2020-04-30 13:24 UTC, mahdi302 commented on app/src/main/java/com/worldsnas/starplayer/view/online_music_list/OnlineMusicListFragment.kt
> + * created by Roohandeh  4/29/2020
Kole klass ro ?

2020-05-02 08:57 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/view/online_music_list/OnlineMusicListFragment.kt
> +    lateinit var onlineMusicListViewModel: OnlineMusicListViewModel
tip : viewmodel module ro bbinid

2020-05-02 08:58 UTC, neptu39701 commented on app/src/main/java/com/worldsnas/starplayer/view/online_music_list/OnlineMusicListFragment.kt
> + * created by Roohandeh  4/29/2020
comment ro pak konid

2020-05-02 09:53 UTC, mehdirouhandeh commented on app/src/main/java/com/worldsnas/starplayer/view/online_music_list/OnlineMusicListFragment.kt
> +    lateinit var onlineMusicListViewModel: OnlineMusicListViewModel
ok

2020-05-02 19:20 UTC, mahdi302 commented
taghirate gofte shode anjam shod. age dobare moshkeli blood begid. 5.2.2020

2020-05-07 10:10 UTC, closed without merging